include:
  - "README.md"
  - "README.zh_CN.md"
  - "guide/Abbreviation.md"
  - "guide/Abbreviation.zh_CN.md"
  - "guide/Compliance.md"
  - "guide/Compliance.zh_CN.md"
  - "guide/Rawdata.md"
  - "guide/Rawdata.zh_CN.md"
permalinks:
  pretty: true